import pygame

# Initialize Pygame
pygame.init()

# Set up the window dimensions
width, height = 800, 600

# Create the window
screen = pygame.display.set_mode((width, height))

# Button Dimensions
button_width, button_height = 50, 50
column_bet_width, column_bet_height = 100, 50
three12_width, three12_height = 200, 50
other_bets_width, other_bets_height = 100, 50

# Create font
font = pygame.font.SysFont(None, 25)
title_font = pygame.font.SysFont(None, 96)
small_font = pygame.font.SysFont(None, 36)

# used colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 50, 160)
GREEN = (0, 100, 0)
GREEN0 = (0, 255, 0)
GREEN1 = (0, 150, 25)
GREEN2 = (0, 50, 0)
GREEN3 = (0, 25, 0)
RED = (255, 0, 0)

# Out of Board Bets
first12 = pygame.Rect(80, 350, three12_width, three12_height)
second12 = pygame.Rect(280, 350, three12_width, three12_height)
third12 = pygame.Rect(480, 350, three12_width, three12_height)
button_1to18 = pygame.Rect(80, 400, other_bets_width, button_height)
even = pygame.Rect(180, 400, other_bets_width, other_bets_height)
red = pygame.Rect(280, 400, other_bets_width, other_bets_height)
black = pygame.Rect(380, 400, other_bets_width, other_bets_height)
odd = pygame.Rect(480, 400, other_bets_width, other_bets_height)
button_19to36 = pygame.Rect(580, 400, other_bets_width, other_bets_height)


# Top Row
button0 = pygame.Rect(30, 200, button_width, button_height*3)
button3 = pygame.Rect(80, 200, button_width, button_height)
button6 = pygame.Rect(130, 200, button_width, button_height)
button9 = pygame.Rect(180, 200, button_width, button_height)
button12 = pygame.Rect(230, 200, button_width, button_height)
button15 = pygame.Rect(280, 200, button_width, button_height)
button18 = pygame.Rect(330, 200, button_width, button_height)
button21 = pygame.Rect(380, 200, button_width, button_height)
button24 = pygame.Rect(430, 200, button_width, button_height)
button27 = pygame.Rect(480, 200, button_width, button_height)
button30 = pygame.Rect(530, 200, button_width, button_height)
button33 = pygame.Rect(580, 200, button_width, button_height)
button36 = pygame.Rect(630, 200, button_width, button_height)
top_column_bet = pygame.Rect(680, 200, column_bet_width, column_bet_height)

# Middle Row
button2 = pygame.Rect(80, 250, button_width, button_height)
button5 = pygame.Rect(130, 250, button_width, button_height)
button8 = pygame.Rect(180, 250, button_width, button_height)
button11 = pygame.Rect(230, 250, button_width, button_height)
button14 = pygame.Rect(280, 250, button_width, button_height)
button17 = pygame.Rect(330, 250, button_width, button_height)
button20 = pygame.Rect(380, 250, button_width, button_height)
button23 = pygame.Rect(430, 250, button_width, button_height)
button26 = pygame.Rect(480, 250, button_width, button_height)
button29 = pygame.Rect(530, 250, button_width, button_height)
button32 = pygame.Rect(580, 250, button_width, button_height)
button35 = pygame.Rect(630, 250, button_width, button_height)
middle_column_bet = pygame.Rect(680, 250, column_bet_width, column_bet_height)

# Bottom Row
button1 = pygame.Rect(80, 300, button_width, button_height)
button4 = pygame.Rect(130, 300, button_width, button_height)
button7 = pygame.Rect(180, 300, button_width, button_height)
button10 = pygame.Rect(230, 300, button_width, button_height)
button13 = pygame.Rect(280, 300, button_width, button_height)
button16 = pygame.Rect(330, 300, button_width, button_height)
button19 = pygame.Rect(380, 300, button_width, button_height)
button22 = pygame.Rect(430, 300, button_width, button_height)
button25 = pygame.Rect(480, 300, button_width, button_height)
button28 = pygame.Rect(530, 300, button_width, button_height)
button31 = pygame.Rect(580, 300, button_width, button_height)
button34 = pygame.Rect(630, 300, button_width, button_height)
bottom_column_bet = pygame.Rect(680, 300, column_bet_width, column_bet_height)


# Puts labels on button
# Out of Board Bets
first12_text = font.render("First 12", True, WHITE)
second12_text = font.render("Second 12", True, WHITE)
third12_text = font.render("Third 12", True, WHITE)
button_1to18_text = font.render("1 to 18", True, WHITE)
button_19to36_text = font.render("19 to 36", True, WHITE)
even_text = font.render("Even", True, WHITE)
odd_text = font.render("Odd", True, WHITE)
red_text = font.render("Red", True, WHITE)
black_text = font.render("Black", True, WHITE)

# Top Row
button0_text = font.render("0", True, BLACK)
button3_text = font.render("3", True, WHITE)
button6_text = font.render("6", True, WHITE)
button9_text = font.render("9", True, WHITE)
button12_text = font.render("12", True, WHITE)
button15_text = font.render("15", True, WHITE)
button18_text = font.render("18", True, WHITE)
button21_text = font.render("21", True, WHITE)
button24_text = font.render("24", True, WHITE)
button27_text = font.render("27", True, WHITE)
button30_text = font.render("30", True, WHITE)
button33_text = font.render("33", True, WHITE)
button36_text = font.render("36", True, WHITE)
top_column_text = font.render("2 for 1", True, WHITE)

# Middle Row
button2_text = font.render("2", True, WHITE)
button5_text = font.render("5", True, WHITE)
button8_text = font.render("8", True, WHITE)
button11_text = font.render("11", True, WHITE)
button14_text = font.render("14", True, WHITE)
button17_text = font.render("17", True, WHITE)
button20_text = font.render("20", True, WHITE)
button23_text = font.render("23", True, WHITE)
button26_text = font.render("26", True, WHITE)
button29_text = font.render("29", True, WHITE)
button32_text = font.render("32", True, WHITE)
button35_text = font.render("35", True, WHITE)
middle_column_text = font.render("2 for 1", True, WHITE)

# Bottom Row
button1_text = font.render("1", True, WHITE)
button4_text = font.render("4", True, WHITE)
button7_text = font.render("7", True, WHITE)
button10_text = font.render("10", True, WHITE)
button13_text = font.render("13", True, WHITE)
button16_text = font.render("16", True, WHITE)
button19_text = font.render("19", True, WHITE)
button22_text = font.render("22", True, WHITE)
button25_text = font.render("25", True, WHITE)
button28_text = font.render("28", True, WHITE)
button31_text = font.render("31", True, WHITE)
button34_text = font.render("34", True, WHITE)
bottom_column_text = font.render("2 for 1", True, WHITE)


def create_board():
    # Creates buttons for Board
    # Off Board Bets
    pygame.draw.rect(screen, GREEN1, first12)
    pygame.draw.rect(screen, GREEN2, second12)
    pygame.draw.rect(screen, GREEN1, third12)
    pygame.draw.rect(screen, GREEN2, button_1to18)
    pygame.draw.rect(screen, GREEN3, button_19to36)
    pygame.draw.rect(screen, GREEN3, even)
    pygame.draw.rect(screen, GREEN2, odd)
    pygame.draw.rect(screen, RED, red)
    pygame.draw.rect(screen, BLACK, black)
    screen.blit(first12_text, (first12.x + 70, first12.y + 10))
    screen.blit(second12_text, (second12.x + 65, second12.y + 10))
    screen.blit(third12_text, (third12.x + 70, third12.y + 10))
    screen.blit(button_1to18_text, (button_1to18.x + 25, button_1to18.y + 15))
    screen.blit(button_19to36_text, (button_19to36.x + 20, button_19to36.y + 15))
    screen.blit(even_text, (even.x + 30, even.y + 15))
    screen.blit(odd_text, (odd.x + 30, odd.y + 15))
    screen.blit(red_text, (red.x + 30, red.y + 15))
    screen.blit(black_text, (black.x + 30, black.y + 15))


    # Green 0
    pygame.draw.rect(screen, GREEN0, button0)
    screen.blit(button0_text, (button0.x + 20, button3.y + 65))
    # Top Row
    pygame.draw.rect(screen, RED, button3)
    pygame.draw.rect(screen, BLACK, button6)
    pygame.draw.rect(screen, RED, button9)
    pygame.draw.rect(screen, RED, button12)
    pygame.draw.rect(screen, BLACK, button15)
    pygame.draw.rect(screen, RED, button18)
    pygame.draw.rect(screen, RED, button21)
    pygame.draw.rect(screen, BLACK, button24)
    pygame.draw.rect(screen, RED, button27)
    pygame.draw.rect(screen, RED, button30)
    pygame.draw.rect(screen, BLACK, button33)
    pygame.draw.rect(screen, RED, button36)
    pygame.draw.rect(screen, GREEN2, top_column_bet)
    screen.blit(button3_text, (button3.x + 20, button3.y + 15))
    screen.blit(button6_text, (button6.x + 20, button6.y + 15))
    screen.blit(button9_text, (button9.x + 20, button9.y + 15))
    screen.blit(button12_text, (button12.x + 15, button12.y + 15))
    screen.blit(button15_text, (button15.x + 15, button15.y + 15))
    screen.blit(button18_text, (button18.x + 15, button18.y + 15))
    screen.blit(button21_text, (button21.x + 15, button21.y + 15))
    screen.blit(button24_text, (button24.x + 15, button24.y + 15))
    screen.blit(button27_text, (button27.x + 15, button27.y + 15))
    screen.blit(button30_text, (button30.x + 15, button30.y + 15))
    screen.blit(button33_text, (button33.x + 15, button33.y + 15))
    screen.blit(button36_text, (button36.x + 15, button36.y + 15))
    screen.blit(top_column_text, (top_column_bet.x + 25, top_column_bet.y + 15))

    # Middle Row
    pygame.draw.rect(screen, BLACK, button2)
    pygame.draw.rect(screen, RED, button5)
    pygame.draw.rect(screen, BLACK, button8)
    pygame.draw.rect(screen, BLACK, button11)
    pygame.draw.rect(screen, RED, button14)
    pygame.draw.rect(screen, BLACK, button17)
    pygame.draw.rect(screen, BLACK, button20)
    pygame.draw.rect(screen, RED, button23)
    pygame.draw.rect(screen, BLACK, button26)
    pygame.draw.rect(screen, BLACK, button29)
    pygame.draw.rect(screen, RED, button32)
    pygame.draw.rect(screen, BLACK, button35)
    pygame.draw.rect(screen, GREEN1, middle_column_bet)
    screen.blit(button2_text, (button2.x + 20, button2.y + 15))
    screen.blit(button5_text, (button5.x + 20, button5.y + 15))
    screen.blit(button8_text, (button8.x + 20, button8.y + 15))
    screen.blit(button11_text, (button11.x + 15, button11.y + 15))
    screen.blit(button14_text, (button14.x + 15, button14.y + 15))
    screen.blit(button17_text, (button17.x + 15, button17.y + 15))
    screen.blit(button20_text, (button20.x + 15, button20.y + 15))
    screen.blit(button23_text, (button23.x + 15, button23.y + 15))
    screen.blit(button26_text, (button26.x + 15, button26.y + 15))
    screen.blit(button29_text, (button29.x + 15, button29.y + 15))
    screen.blit(button32_text, (button32.x + 15, button32.y + 15))
    screen.blit(button35_text, (button35.x + 15, button35.y + 15))
    screen.blit(middle_column_text, (middle_column_bet.x + 25, middle_column_bet.y + 15))

    # Bottom Row
    pygame.draw.rect(screen, RED, button1)
    pygame.draw.rect(screen, BLACK, button4)
    pygame.draw.rect(screen, RED, button7)
    pygame.draw.rect(screen, BLACK, button10)
    pygame.draw.rect(screen, BLACK, button13)
    pygame.draw.rect(screen, RED, button16)
    pygame.draw.rect(screen, RED, button19)
    pygame.draw.rect(screen, BLACK, button22)
    pygame.draw.rect(screen, RED, button25)
    pygame.draw.rect(screen, BLACK, button28)
    pygame.draw.rect(screen, BLACK, button31)
    pygame.draw.rect(screen, RED, button34)
    pygame.draw.rect(screen, GREEN2, bottom_column_bet)
    screen.blit(button1_text, (button1.x + 20, button1.y + 15))
    screen.blit(button4_text, (button4.x + 20, button4.y + 15))
    screen.blit(button7_text, (button7.x + 20, button7.y + 15))
    screen.blit(button10_text, (button10.x + 15, button10.y + 15))
    screen.blit(button13_text, (button13.x + 15, button13.y + 15))
    screen.blit(button16_text, (button16.x + 15, button16.y + 15))
    screen.blit(button19_text, (button19.x + 15, button19.y + 15))
    screen.blit(button22_text, (button22.x + 15, button22.y + 15))
    screen.blit(button25_text, (button25.x + 15, button25.y + 15))
    screen.blit(button28_text, (button28.x + 15, button28.y + 15))
    screen.blit(button31_text, (button31.x + 15, button31.y + 15))
    screen.blit(button34_text, (button34.x + 15, button34.y + 15))
    screen.blit(bottom_column_text, (bottom_column_bet.x + 25, bottom_column_bet.y + 15))

    pygame.display.flip()
